### ISSUE TITLE
[BUG] Can't open the configuration window

### ISSUE THREAD

**Issue by MastaGooz** [p4535992/foundryvtt-rarity-colors#10]
**Module Version:** v0.3.9

Hi, 

I'm trying to test this module for Custom System Builder and I'm getting this console error when I try to open the "Rarity Color Configuration" in the module settings.

![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/149971487/eddf7fa5-73a6-41dd-b6f2-ebaec50f416c)

**Comment by p4535992** [comment]
Try to fix this on 0.3.11

**Comment by MastaGooz** [comment]
Just tried the 0.3.11, but the same bug is still there

**Comment by Fabbe** [comment]
Same problem here

**Comment by p4535992** [comment]
Try to fix again this on 0.3.21 .
