### ISSUE TITLE
[BUG] Feat colors not chaning

### ISSUE THREAD

**Issue by ChthonicKnight** [p4535992/foundryvtt-rarity-colors#12]
**Module Version:** v0.3.11
[Console.txt](https://github.com/p4535992/foundryvtt-rarity-colors/files/14159076/Console.txt)

**Describe the bug**
Updated the color for the feats within the settings however it is just keeping the default colors (blue) on all of the feats.

**To Reproduce**
Set the colors in the settings:
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/9ccc7da1-e045-432b-967e-08ec5683dfba)

Check the box to enable colors:
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/9c2127f1-7e54-44b5-8f17-f79f86a5bcae)

Check the feats:
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/37e9ccab-45af-4fe0-8ffc-f3d123a33b36)
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/4a6dc5e4-7b7f-4098-a328-10d122989186)

**Expected behavior**
Should show the correct color

**Browser:**
Foundry browser

**Foundry Version:** 
11.315
**Game System:** 
DND5e 2.4.1
**Additional context**
Tested without any other modules except Color lib

**Comment by p4535992** [comment]
Ty for the detailed ticket and sorry for the delay.
Fixed on 0.3.12

**Comment by ChthonicKnight** [comment]
Looks like all are fixed except the regular Feat
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/e483b9da-888e-455e-a5fe-682dd2027264)
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/d304ca25-d49a-4d93-a760-f04b53b13544)

**Comment by p4535992** [comment]
sorry didn't have the time to test all the use cases, should be fixed on 0.3.13
