### ISSUE TITLE
DDB-Importer compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [p4535992/foundryvtt-rarity-colors#14]
I have also logged this issue with DDB-Importer issue [469](https://github.com/MrPrimate/ddb-importer/issues/469#issue-2186662435)

When doing spell/item munching Rarity Colors lags out the muncher severely and throws a lot of errors. I am hoping on one side or the other something can be done to fix or mitigate the issue.

**Comment by p4535992** [comment]
It's probably some bad behavior on my side, the fast and simple solution is just to disable the module while importing and re-enable later

```
game.settings.set("rarity-colors", "rarityFlag", false)

// DO SOMETHING

game.settings.set("rarity-colors", "rarityFlag", true)

```
