### ISSUE TITLE
Feature: No bg OR text, only item.

### ISSUE THREAD

**Issue by Sayshal** [p4535992/foundryvtt-rarity-colors#16]
Hey! The latest updated added:

> Add new feature : Border color on itme images

The setting above it allows for coloring the background and not text

What I'd like to be able to do is highlight ONLY the image border, but the setting above only allows "A" or "B", not "Off". I recommend  making the setting above the new setting a drop down with the options "None, Background Coloring, Text Coloring"

**Comment by p4535992** [comment]
Done on 0.3.18
