### ISSUE TITLE
D&D5e New Feat Type Compatability

### ISSUE THREAD

**Issue by ChthonicKnight** [p4535992/foundryvtt-rarity-colors#17]
There is a new feature type within the new 3.0 release labeled Supernatural Gift.
Would be cool to be able to change the feature color for this one to separate from the rest.
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/ba27d64d-6466-4d70-97be-ace5713b9acb)

Tried doing it manually from settings but doesn't allow to enter the name:
![2024-04-30_14-14-22](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/4cab4af1-a4e4-41dc-86cf-5462612efa32)

**Comment by p4535992** [comment]
Hey ty for make me notice this bug, by the way  i like your choice of colors, did you also choose the colors for the spellchools by chance ?

**Comment by ChthonicKnight** [comment]
I have not yet, just items and class features right now.

**Comment by p4535992** [comment]
Should be fixed on 0.3.19 , but if you do a "Reset Settings" of the module tha feature will be loaded automatically.
Let me know it if everything is working as expected

**Comment by ChthonicKnight** [comment]
Okay managed to get it saved, however doesn't seem to like the alternate color.
updated to 0.3.19
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/898da92a-047b-4a3f-8a8c-57178a853afa)
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/21301107/67eec144-2c3a-4601-8ac3-bfdd55adb28b)

**Comment by ChthonicKnight** [comment]
I'll try a reset see if that helps.

**Comment by ChthonicKnight** [comment]
Oh yeah nvm, doing a reset fixed it! so we are all good now.
