### ISSUE TITLE
[BUG] Colors not showing on the new character sheet

### ISSUE THREAD

**Issue by Yagoks** [p4535992/foundryvtt-rarity-colors#19]
**Module Version:** v0.3.21

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Colors are not appearing on the new character sheet, in the new NPC's Sheets are working as should.

TypeError: Cannot set property message of  which has only a getter
    at Hooks.onError (foundry.js:752:30)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:734:36)
    at Hooks.callAll (foundry.js:687:17)
    at ActorSheet5eCharacter2.renderPatch (application-render.js:78:15)
    at async ActorSheet5eCharacter2._render (foundry.js:6532:5)
    at async ActorSheet5eCharacter2._render (character-sheet-2.mjs:76:5)

**To Reproduce**
1. Go to 'Character sheet'
2. See Error

**Expected behavior**
Expected to see the colors in the features, spells and items

**Screenshots**
![image](https://github.com/user-attachments/assets/d8f434be-57ad-4dfc-888e-9d4cd5d5509b)
![image](https://github.com/user-attachments/assets/b08de976-1e3e-4e09-b51f-07b422f4521e)
![image](https://github.com/user-attachments/assets/4fa71bc2-7fb8-42da-ba71-4f28d28ed421)

**Browser:**
 - Chrome

**Foundry Version:** 
V11 Stable - Patch 13 (Build315)
**Game System:** 
Dungeons & Dragons Fifth Edition (3.3.0)

**Comment by p4535992** [comment]
Cannot replicate , can you pass to me the acro json data (rename the .json to .txt to attach the file on github)

**Comment by Yagoks** [comment]
Can you tell where i can find this acro json data?

**Comment by p4535992** [comment]
> Can you tell where i can find this acro json data?

A sorry "actor json data", just right click on the actor entity on the actor sidebar (the one on the right) and click on the voice "Export Data" a file json is donwloaded on your macine rename that file from xxx.json to xxx.txt and attach on this issue

**Comment by Yagoks** [comment]
Here it's, i choosed the sheet on the prints, if you wanted a sheet with less things, let me know.

[xxx.txt](https://github.com/user-attachments/files/16752053/xxx.txt)

Edit:  i uploaded the wrong json, now its right
