### ISSUE TITLE
Showing not compatible with V11

### ISSUE THREAD

**Issue by MentalyUnsound** [p4535992/foundryvtt-rarity-colors#2]
Showing not compatible with version 11.

**Comment by Fridan99** [comment]
V11 migration?

**Comment by Fridan99** [comment]
v. 0.2.4

Apparently it does not appear in the list in-world modules, so it cannot be installed. Being a fairly "simple" module, it is most likely a version problem. 

![1 1](https://github.com/p4535992/foundryvtt-rarity-colors/assets/86131373/d4a0494e-c64b-4d57-96da-3cd6f53bb76d)

I have found that you only have to change line 54 of the module.json 
**"maximum": "10"** to **"maximum": "11"**

This fixes the problem. :), so its just only a versioning problem. For the rest, the module apparently works as intended.
