### ISSUE TITLE
Opton to hide the rarity color when an item is not identified

### ISSUE THREAD

**Issue by ChthonicKnight** [p4535992/foundryvtt-rarity-colors#22]
Would be nice to see an option within Rarity Colors to hide the color of the item when it is not identified:

How it currently shows within DnD5e
![image](https://github.com/user-attachments/assets/aa7ed6e9-953f-4d23-bc23-31045aae5fcb)

How it shows in Tidy 5e
![image](https://github.com/user-attachments/assets/f4acfa9e-4cbe-4ca9-84f1-af67e0e4969e)

**Comment by p4535992** [comment]
Add the control on 12.0.0

**Comment by ChthonicKnight** [comment]
Wonderful! Thank you for the quick turnaround!
