### ISSUE TITLE
Rarity Colors for features not working after update

### ISSUE THREAD

**Issue by ChthonicKnight** [p4535992/foundryvtt-rarity-colors#24]
Foundry v12.331
System dnd5e v3.3.1
Rarity Colors v12.0.0
Other modules enabled: lib - Color Settings

**Describe the bug**
Colors are configured for features but are not showing after update.
![image](https://github.com/user-attachments/assets/bdf3c2f5-a46f-4105-955f-3f42bfef119d)
![image](https://github.com/user-attachments/assets/c4ad879a-9f40-45bd-a6ab-214ac8cf7839)

I also attempted to reset the settings and the same result occurs.

**To Reproduce**
1. Configure or reset Rarity color settings to have colors for features.
2. Open character sheet and navigate to features, see that none are colored.

**Browser:**
Edge

**Comment by p4535992** [comment]
sorry sorry sorry should be  fixed on 12.0.1

**Comment by ChthonicKnight** [comment]
All is well now, thank you for efforts!
