### ISSUE TITLE
[BUG] Rarity colors for feats don't respect color coding 

### ISSUE THREAD

**Issue by Opius134** [p4535992/foundryvtt-rarity-colors#3]
[192.168.0.110-1694983582091.log](https://github.com/p4535992/foundryvtt-rarity-colors/files/12643689/192.168.0.110-1694983582091.log)

**Describe the bug**
When changing the rarity colors of class and background features, the only colors that show on the sheets are blue.

**To Reproduce**
1. Enable mod
2. Go to settings, edit class feature type colors
3. Check on any character sheet
4. No errors reported on console

**Expected behavior**
The colors on the sheet should reflect the different sources for features, but all appear to be a default blue color. 

**Screenshots**
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/100728089/ac8e30da-c745-45a0-adb8-462bf1c4b65e)
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/100728089/fdf24c74-4af7-4fd3-b2b2-54043b7ce506)
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/100728089/0c2e67e8-e71e-4438-ae44-d5a93ec2b9fe)
![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/100728089/16ed0ba4-7502-4a92-ba1a-b1e49a72203e)

**Browser:**
Brave Browser and Firefox

**Foundry Version:** 
Version 11 Stable, 11.308

**Game System:** 
dnd5e, 2.3.1

**Additional context**
When testing with no other modules installed the problem seems to persist.

**Comment by p4535992** [comment]
Sadly  for annoying issue with colorsettings, i just replace the colorpicker with the html standard... should be pathced on 0.3.3

**Comment by Opius134** [comment]
Tested on 0.3.3. So far no luck. I've disabled all other modules except module profiles and the color-lib dependency. 

![image](https://github.com/p4535992/foundryvtt-rarity-colors/assets/100728089/b502aaae-8148-467c-a086-e9e9b88d58a2)
I also can't get 'add class feature type' button to work. 

Even as it is, the module is still quite good.  Thank you for the continued work!
