### ISSUE TITLE
Is it possible to get Rarity Color to displaying in Favorite Items?

### ISSUE THREAD

**Issue by SirAron111** [p4535992/foundryvtt-rarity-colors#4]
I noticed that the Rarity Color doesn't display in the Favorite items section. Is it possible to make that possible as well?

![Unbenannt](https://github.com/p4535992/foundryvtt-rarity-colors/assets/39855956/f29384a3-a407-4b1c-ae26-24c9bd29ec3b)
![Unbenannt2](https://github.com/p4535992/foundryvtt-rarity-colors/assets/39855956/751ba537-9256-4cdf-b649-0b8a6ff32e2d)

**Comment by p4535992** [comment]
There is a API for module intercompatibility
