### ISSUE TITLE
[Suggestion] Expose API method to get the color from an item

### ISSUE THREAD

**Issue by Haxxer** [p4535992/foundryvtt-rarity-colors#5]
Rarity Colors is supported in Item Piles, and I would like to be able to retrieve the color of any given item.

If possible, something like this would be nice:
```js
const color = game.modules.get("rarity-colors").api.getColorForItem(item);
```
The return value could be a color hex code string or false if no color was found for the given item.

**Comment by p4535992** [comment]
Sure

**Comment by p4535992** [comment]
Done with 0.3.5, https://github.com/p4535992/foundryvtt-rarity-colors/blob/master/wiki/api.md.
Let me know it if is enough.
