### ISSUE TITLE
[BUG] Since the last update, using the "rarity color only as background not text" setting makes text black and nearly unreadable

### ISSUE THREAD

**Issue by SirAron111** [p4535992/foundryvtt-rarity-colors#6]
**Module Version:** v0.0.0

**Before open any issue**

[localhost-1701980530973.log](https://github.com/p4535992/foundryvtt-rarity-colors/files/13604957/localhost-1701980530973.log)

**Describe the bug**
The Colors of the text from items is nearly unreadable if it turns Black due to setting the background as the colored part..

**To Reproduce**
1. Set the setting rarity color only as background not text to true
2. watch the text turn black and become nearly unreadable on the darker colors.

**Expected behavior**
i like the background colored more than the text, but the text should still be readable.

**Screenshots**
![Unbenannt](https://github.com/p4535992/foundryvtt-rarity-colors/assets/39855956/c068cd09-0146-41fe-bf8d-7ca916eaedcf)

**Foundry Version:** 
V11

**Game System:** 
DnD5E

**Comment by p4535992** [comment]
Try to fix this on 0.3.8

**Comment by SirAron111** [comment]
Mostly fixed, but not for Legendary Items and Artifacts.
![Unbenannt](https://github.com/p4535992/foundryvtt-rarity-colors/assets/39855956/ccf004c3-ce7c-4ec3-8d14-1b2bf695c7c3)

**Comment by p4535992** [comment]
After many tests, i can confirm is not a bug... according to the [HSP Color Model — Alternative to HSV (HSB) and HSL](https://alienryderflex.com/hsp.html) and testing with three different libraries ..

Also i think you are using the tidy sheet kgar ? If is this the case the color picker is separated... you must use the color picker on that module or ask for a better integration with this module.

On the new version 0.3.10 i add some module settings for customize the color threshold and the alpha value.

**Comment by SirAron111** [comment]
The last update fixed it. Thanks for the hard work and great modules.
